Finished response page skeleton
cse110-sp23-group16/cse110-sp23-group16 pull request #16
Opened 2023-05-12 08:00 UTC by Chengqianc

Rendered correctly and passed validation.

2023-05-12 18:52 UTC, ShashankVenkatramani commented
The page looks great! Unsure about the in html styles, and the script tag since we have dedicated css and js files, however we haven't really talked about style guidelines yet so we can confirm this in the meeting today.

2023-05-13 19:01 UTC, ShashankVenkatramani requested changes
Separate the style and script into respective files as decided in the meeting.

2023-05-14 20:39 UTC, Chengqianc commented
Just separated style and script into their respective files.

2023-05-15 03:42 UTC, ChiSengWong approved these changes

2023-05-15 03:49 UTC, merged