Jsdoc
cse110-sp23-group16/cse110-sp23-group16 pull request #71
Opened 2023-05-27 08:34 UTC by khushijpatel

JSDocs is installed and documents in the folder called docs are generated using github actions

https://github.com/cse110-sp23-group16/cse110-sp23-group16/actions/runs/5097904579

2023-05-31 01:16 UTC, ChiSengWong commented
can you resolve the conflict?

2023-06-01 22:14 UTC, VictorKuu approved these changes, later dismissed

2023-06-02 00:03 UTC, ShashankVenkatramani requested changes
Do not merge, code is completely non-functional at the moment

~ The person who pushed the last commit :P

2023-06-02 18:50 UTC, ShashankVenkatramani approved these changes
Looks good!

2023-06-02 18:51 UTC, merged